import 'package:flutter/material.dart';

class DecryptionView extends StatelessWidget {
  const DecryptionView({
    super.key,
    required this.formKey,
    required this.payloadController,
    required this.passwordController,
    required this.notesController,
    required this.isProcessing,
    required this.onDecrypt,
    this.lastError,
  });

  final GlobalKey<FormState> formKey;
  final TextEditingController payloadController;
  final TextEditingController passwordController;
  final TextEditingController notesController;
  final bool isProcessing;
  final VoidCallback onDecrypt;
  final String? lastError;

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Form(
        key: formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Decrypt payload',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 12),
            Text('Paste the payload generated by the encryption tool.'),
            const SizedBox(height: 24),
            TextFormField(
              controller: payloadController,
              minLines: 6,
              maxLines: 12,
              decoration: const InputDecoration(
                labelText: 'Encrypted payload',
                alignLabelWithHint: true,
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Enter the encrypted payload to continue';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: passwordController,
              decoration: const InputDecoration(labelText: 'Password'),
              obscureText: true,
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Password required';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: notesController,
              decoration: const InputDecoration(labelText: 'Notes (optional)'),
              maxLines: 3,
            ),
            const SizedBox(height: 16),
            if (lastError != null)
              Padding(
                padding: const EdgeInsets.only(bottom: 16),
                child: Text(
                  lastError!,
                  style: TextStyle(color: Theme.of(context).colorScheme.error),
                ),
              ),
            FilledButton.icon(
              onPressed: isProcessing ? null : onDecrypt,
              icon: isProcessing
                  ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Icons.lock_open),
              label: Text(isProcessing ? 'Decrypting…' : 'Decrypt now'),
            ),
          ],
        ),
      ),
    );
  }
}
