name: navy_encrypt
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString wAdvertisinghile build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+3

# Flutter Version 3.3.8
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02
  #  share_plus:
  #    git:
  #      url: https://github.com/fluttercommunity/plus_plugins.git
  #      path: packages/share_plus/share_plus
  #      ref: 7b6ac7ebc33e3bfd023030e61268cff0fa03d913



  flutter_icons: ^1.1.0
  google_fonts: ^2.0.0
  encrypt: ^5.0.0
  modal_bottom_sheet: ^2.1.2
  intl: ^0.17.0
  path_provider: ^2.0.1
  receive_sharing_intent: ^1.4.5
  image_picker: ^0.8.3+3

  file_picker: ^4.6.1
  #  file_picker: ^4.5.1
  file_picker_cross: ^4.6.0
  path: ^1.8.0
  #  share_plus: ^2.1.4
  share_plus: ^4.0.4
  flutter_absolute_path: ^1.0.6
  #uri_to_file: ^0.1.3
  photo_view: ^0.12.0
  line_icons: ^2.0.1
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
  mime: ^1.0.0
  mime_type: ^1.0.0
  uuid: ^3.0.4
  archive: ^3.4.2
  image: ^3.0.5
  universal_html: ^1.2.1
  #  permission_handler: ^10.4.3
  permission_handler: ^11.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.0.6
  firebase_core: ^2.0.0
  #  firebase_auth: ^3.1.2
  googleapis: ^5.0.1
  google_sign_in: ^5.1.1
  flutter_breadcrumb: ^1.0.1
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.8
  #flutter_glow: ^0.2.0
  flutter_secure_storage: ^4.2.1
  flutter_web_auth: ^0.3.1
  device_info_plus: ^3.1.0
  provider: ^6.0.1
  page_transition: ^2.0.4
  url_launcher: ^6.1.7
  oauth2: ^2.0.0
  image_gallery_saver: ^1.7.1
  desktop_window: ^0.4.0
  flutter_signin_button: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  icloud_storage: ^0.2.1
  is_first_run: ^1.0.0
  multi_select_flutter: ^4.1.3
  printing: ^5.9.3
#  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  platform: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # mdpi        1.0x
  # hdpi        1.5x
  # xhdpi       2.0x
  # xxhdpi      3.0x
  # xxxhdpi     4.0x

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/win/
    - assets/images/logos/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: DBHeavent
      fonts:
        - asset: assets/fonts/DB_Heavent_v3.2.ttf
        - asset: assets/fonts/DB_Heavent_Med_v3.2.ttf
          weight: 700