name: navy_encrypt
description: Navy Encrypt cross-platform secure encryption utility.
publish_to: 'none'
version: 3.3.8+8

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  pointycastle: ^3.7.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/win/
    - assets/images/logos/
  fonts:
    - family: DBHeavent
      fonts:
        - asset: assets/fonts/DB_Heavent_v3.2.ttf
        - asset: assets/fonts/DB_Heavent_Med_v3.2.ttf
          weight: 700
