import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../core/utils/platform_utils.dart';
import '../../shared/widgets/responsive_section.dart';
import '../decryption/decryption_page.dart';
import '../encryption/encryption_page.dart';
import '../result/result_page.dart';
import '../settings/settings_page.dart';

class HomeView extends StatelessWidget {
  const HomeView({super.key});

  @override
  Widget build(BuildContext context) {
    return ListView(
      padding: const EdgeInsets.all(24),
      children: [
        Text(
          'Secure Navy-grade encryption for everyone',
          style: Theme.of(context).textTheme.headlineSmall,
        ),
        const SizedBox(height: 12),
        Text(
          'Start by encrypting a document, decrypting a message, or reviewing your latest results.',
          style: Theme.of(context).textTheme.bodyLarge,
        ),
        const SizedBox(height: 24),
        Wrap(
          spacing: 16,
          runSpacing: 16,
          children: [
            _ActionCard(
              title: 'Encrypt',
              description:
                  'Protect a file or paste any text to secure it with AES-256 encryption.',
              icon: Icons.lock,
              color: Colors.teal,
              onTap: () => context.go('/${EncryptionPage.routeSegment}'),
            ),
            _ActionCard(
              title: 'Decrypt',
              description:
                  'Unlock encrypted payloads generated by the app with the correct passphrase.',
              icon: Icons.lock_open,
              color: Colors.orange,
              onTap: () => context.go('/${DecryptionPage.routeSegment}'),
            ),
            _ActionCard(
              title: 'Results',
              description:
                  'Review the most recent encryption or decryption summaries and export them.',
              icon: Icons.receipt_long,
              color: Colors.indigo,
              onTap: () => context.go('/${ResultPage.routeSegment}'),
            ),
            _ActionCard(
              title: 'Settings',
              description:
                  'Configure security preferences, theme, language and desktop behaviours.',
              icon: Icons.settings,
              color: Colors.pink,
              onTap: () => context.go('/${SettingsPage.routeSegment}'),
            ),
          ],
        ),
        const SizedBox(height: 32),
        const ResponsiveSection(),
        const SizedBox(height: 32),
        if (isDesktop)
          Card(
            margin: EdgeInsets.zero,
            child: ListTile(
              leading: const Icon(Icons.computer),
              title: const Text('Desktop experience'),
              subtitle: const Text(
                'Optimized controls for Windows with keyboard shortcuts and drag & drop.',
              ),
            ),
          ),
      ],
    );
  }
}

class _ActionCard extends StatelessWidget {
  const _ActionCard({
    required this.title,
    required this.description,
    required this.icon,
    required this.color,
    required this.onTap,
  });

  final String title;
  final String description;
  final IconData icon;
  final Color color;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return SizedBox(
      width: 260,
      child: Card(
        elevation: 2,
        clipBehavior: Clip.antiAlias,
        child: InkWell(
          onTap: onTap,
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                CircleAvatar(
                  backgroundColor: color.withOpacity(0.15),
                  foregroundColor: color,
                  child: Icon(icon),
                ),
                const SizedBox(height: 16),
                Text(title, style: theme.textTheme.titleLarge),
                const SizedBox(height: 8),
                Text(description),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
